# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20180206_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
