# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_hof_posts_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='subject',
            field=models.CharField(default='Maths', max_length=100),
        ),
    ]
