# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-30 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20180210_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slideshow',
            name='created_date',
        ),
        migrations.AddField(
            model_name='slideshow',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
